library (tidyverse)
library (janitor)
library (psych)
survey <- read_csv ("/kaggle/input/diabetes-dataset/ diabetes.csv")
describe(survey)
describe.by(survey, survey$Glucose)
hist(survey$Glucose)
hist (survey$BMI)
plot(density (survey$Glucose))
plot(density (survey $BMI))
plot(survey$BMI ~ survey$Glucose)
barplot(table(survey$Glucose))
barplot(table(survey$BMI))
barplot (table(survey$BMI, survey$Glucose)) barplot(table(survey$BMI,survey$Glucose), beside=TRUE)
plot(survey$Glucose,survey$BMI)
cor(survey$BMI,survey$Glucose)
Model <- Im (BMI - Glucose, data = survey)
summary (Model)
plot(survey$BMI ~ survey$Glucose, xlab="glucose", ylab="bmi")
abline (Model, col-"blue") newdata <- data.frame(Glucose=100) predict (Model, newdata)
describe(survey$BMI)
describe(survey$Glucose)
corr <- cor(survey$BMI,survey$Glucose)
a <- corr* (7.88416/31.97262)
b <- 31.99258 - a* (120.8945)
y <- a* (119)+b
У